# Generated by Django 5.0.3 on 2024-03-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('is_admin', models.BooleanField(default=True)),
                ('is_member', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('isbn', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('pages', models.IntegerField()),
                ('image', models.ImageField(default='default.png', upload_to='images/')),
                ('pdf', models.FileField(default='default.pdf', upload_to='pdfs/')),
            ],
        ),
    ]
